### ISSUE TITLE
Support custom templates with external formatters

### ISSUE THREAD

**Issue by cweill** [cweill/gotests#5]
Sometimes outputting got and want isn't enough. There are many useful OSS packages for generating pretty diffs of strings, structs, slices etc, but it would be unreasonable for this binary to require them as dependencies in the generated test files. 

Instead, if the repository already has the dependency, the template will use it by automatically. This would allow users to created their own custom templates using their in-house tools.

These custom templates could be specified in a json/yaml file that define the template for a result of a given types:

For example if "github.com/tonnerre/golang-pretty" is available:
```yaml
types:  
 - struct
 - map
 - slice
deps: 
 - github.com/tonnerre/golang-pretty
template: >
 if {{.Got}} := {{Func}}({{.Args}}); !reflect.DeepEqual({{.Got}}, tt.{{.Want}}) {
   t.Errorf("%v. {{Func}}() returned diff (want -> got)\n %v", tt.name, pretty.Compare(tt.{{.Want}}), {{.Got}}))
 }
```
This will require a significant (and much needed) refactor of the render package.
